ADD_SCENE(tama_mem, start, Start)
ADD_SCENE(tama_mem, chip_detect, ChipDetect)
ADD_SCENE(tama_mem, chip_detected, ChipDetected)
ADD_SCENE(tama_mem, chip_detect_fail, ChipDetectFail)
ADD_SCENE(tama_mem, select_file, SelectFile)
ADD_SCENE(tama_mem, saved_file_menu, SavedFileMenu)
ADD_SCENE(tama_mem, read, Read)
ADD_SCENE(tama_mem, read_filename, ReadFilename)
ADD_SCENE(tama_mem, delete_confirm, DeleteConfirm)
ADD_SCENE(tama_mem, success, Success)
ADD_SCENE(tama_mem, about, About)
ADD_SCENE(tama_mem, verify, Verify)
ADD_SCENE(tama_mem, file_info, FileInfo)
ADD_SCENE(tama_mem, erase, Erase)
ADD_SCENE(tama_mem, chip_error, ChipError)
ADD_SCENE(tama_mem, verify_error, VerifyError)
ADD_SCENE(tama_mem, write, Write)
ADD_SCENE(tama_mem, storage_error, StorageError)
ADD_SCENE(tama_mem, select_vendor, SelectVendor)
ADD_SCENE(tama_mem, select_model, SelectModel)
ADD_SCENE(tama_mem, wiring, Wiring)
ADD_SCENE(tama_mem, protect, Protect)
ADD_SCENE(tama_mem, tama, Tama)


